--ADICIONAR PERMISSAO PARA SOMENTE LEITURA AO USUARIO
GRANT CONNECT ON DATABASE NOME_BANCO TO NOME_USUARIO;
GRANT USAGE   ON SCHEMA public TO NOME_USUARIO;
GRANT SELECT  ON ALL TABLES    IN SCHEMA public TO NOME_USUARIO;
GRANT SELECT  ON ALL SEQUENCES IN SCHEMA public TO NOME_USUARIO;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO NOME_USUARIO;

--PERMISSAO SOMENTE LEITURA PARA TODAS E FUTURAS TABELAS CRIADAS
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO NOME_USUARIO;